spring.application.name=NoScamGG

# Steam
steam.api-url=https://api.steampowered.com
steam.url=https://steamcommunity.com/openid/login
steam.return-url= https://noscamgg.loca.lt/auth/steam/callback
steam.token=${steamOficialApiKey}

# Steam Web Api
steam.web.api.token = ${steamWebApiKey}
steam.web.api.url = https://www.steamwebapi.com/steam/api/


# H2 Database settings
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA (opcional para criar e mostrar logs)
spring.jpa.hibernate.ddl-auto=create-drop

#Mongo
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=NoScamGG